@echo off
echo Deteniendo contenedores...
docker compose down
echo Eliminando datos de PostgreSQL...
docker volume rm sistema-bibliotecario-resiliente_pgdata 2>nul
echo Reconstruyendo e iniciando...
docker compose up -d --build
echo Abriendo dbgate...
start http://localhost:8081
echo Listo.
